### ISSUE TITLE
No such a file

### ISSUE THREAD

**Issue by lainanhui** [zhiweihu1103/HKGC-HyperFormer#2]
![图片1](https://github.com/zhiweihu1103/HKGC-HyperFormer/assets/85324054/72c0f743-7b40-4c85-a5f2-678c3f9f1c7c)
x想问问作者，安装FastMoe的过程出现了这个问题，请问怎么解决呢

**Comment by zhiweihu1103** [comment]
不好意思，刚看到你的问题，我建议你直接使用我提供的fastmoe工程文件进行源码安装，下载地址是：https://drive.google.com/file/d/1c3ijOe5PacVWyfmD2amUk0dpTbsjIHIS/view

**Comment by lainanhui** [comment]
嗯嗯当时有下载这个的，但是可能是我这边的问题没有办法复现。不好意思打扰您，我想请问您这边新发表的论文《HYPERMONO: A Monotonicity-aware Approach to Hyper-Relational Knowledge Representation》，这篇论文有源码吗请问，如果有的话，方便看一下吗想学习学习，谢谢。&nbsp;


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhiwei ***@***.***&gt;; 
发送时间: 2024年4月28日(星期天) 凌晨1:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhiweihu1103/HKGC-HyperFormer] No such a file (Issue #2)














 
不好意思，刚看到你的问题，我建议你直接使用我提供的fastmoe工程文件进行源码安装，下载地址是：https://drive.google.com/file/d/1c3ijOe5PacVWyfmD2amUk0dpTbsjIHIS/view

**Comment by zhiweihu1103** [comment]
有的，我已经上传到github，但是设置成私密形式了，也用到了fastmoe这个库，不使用这个库中的transformer性能会差异非常大，所以你需要尽量能够安装上这个库，这个库好像对cuda不是很友好，我自己也只能在cuda11的机器上安装成功。

**Comment by lainanhui** [comment]
哈喽，那我想请问设置成私密形式了我要怎么去查找呀，能请问作者大大什么时候会放出来吗，我会尽快安装好fastmoe成功复现的，你提出的模型看着性能太好咯，想学习一下。
非常感谢您的回复！打扰您了！


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhiweihu1103/HKGC-HyperFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月28日(星期天) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhiweihu1103/HKGC-HyperFormer] No such a file (Issue #2)





 
有的，我已经上传到github，但是设置成私密形式了，也用到了fastmoe这个库，不使用这个库中的transformer性能会差异非常大，所以你需要尽量能够安装上这个库，这个库好像对cuda不是很友好，我自己也只能在cuda11的机器上安装成功。

**Comment by zhiweihu1103** [comment]
对于HyperFormer模型，我找到了我当时上传代码前自己跑出来的日志，我马上在这里分享一份给你，以便于你自己安装完fastmoe之后进行对照

**Comment by zhiweihu1103** [comment]
[wikipeople.txt](https://github.com/zhiweihu1103/HKGC-HyperFormer/files/15141420/wikipeople.txt)
[jf17k.txt](https://github.com/zhiweihu1103/HKGC-HyperFormer/files/15141421/jf17k.txt)
[wd50k.txt](https://github.com/zhiweihu1103/HKGC-HyperFormer/files/15141422/wd50k.txt)

**Comment by zhiweihu1103** [comment]
对于HyperMono的代码，我可能暂时没有打算公开，因为那篇文章还在审稿中。希望理解。

**Comment by lainanhui** [comment]
> 对于HyperMono的代码，我可能暂时没有打算公开，因为那篇文章还在审稿中。希望理解。

嗯嗯好，能理解的，那希望作者早日中稿，感谢回复！

**Comment by zhiweihu1103** [comment]
也欢迎随时关注我的其他工作，我们最近会挂出新的论文。

**Comment by lainanhui** [comment]
> 也欢迎随时关注我的其他工作，我们最近会挂出新的论文。

好的，已经关注啦，沾沾科研实力，希望作者早日中稿沾沾喜气

**Comment by zhiweihu1103** [comment]
如果没有别的疑问，我会关掉这个issue，如果有新的问题，可以发送邮件zhiweihu@whu.edu.cn，以免我不能及时看到消息。

**Comment by lainanhui** [comment]
好的，感谢，邮箱已经保存啦，可以关闭这个issue。
