### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by lainanhui** [zhiweihu1103/HKGC-HyperFormer#3]
你好，作者，想问在运行过程中出现这个错误要怎么解决呢
![image](https://github.com/zhiweihu1103/HKGC-HyperFormer/assets/85324054/06f9ac4c-45f0-4294-843e-3ff24c51d80e)

**Comment by zhiweihu1103** [comment]
不好意思，我好像没遇到过这个问题，你的fastmoe安装对的吗？建议去fastmoe项目里面看一下是否安装过程会出现这个错误：https://github.com/laekov/fastmoe/issues?q=is%3Aissue+is%3Aopen+Segmentation+fault

**Comment by chongin119** [comment]
Hello, Authors, I also have the segmentation fault problem while I run the repo **run.sh** with your provided dataset "wd50k". Do you any solution about this problem. Looking forward to get your reply.
![error](https://github.com/user-attachments/assets/4ddbabc4-dbc0-4bd4-8e21-25b94fe013ba)
